### ISSUE TITLE
Some weird results

### ISSUE THREAD

**Issue by singpolyma** [microformats/mf2py#101]
(Probably related to https://github.com/snarfed/granary/issues/145)

https://python.microformats.io/?url=http%3A%2F%2Fbeta.singpolyma.net%2F&parser=html5lib

The name on my hcard author is not parsing out of the `n` or `fn` properties, but just using the whole text contnet of the vcard.

Anything with `rel=tag` gets a weird `data` element appended to the `content.html`

For comparison, https://pin13.net/mf2/?url=http%3A%2F%2Fbeta.singpolyma.net%2F gives me what I expect.

**Comment by kartikprabhu** [comment]
@singpolyma yes it is mf2py backcompat parsing which is doing that.

The name problem should be fixed in a new version. I'll look into the `content.html` one.

**Comment by kartikprabhu** [comment]
Minimal example for the `content.html` issue above.

```html
<article class="hentry">
    <section class="entry-content">
        <p>This is <a href="/tags/mytag" rel="tag">mytag</a> inside content</p>
    </section>
</article>
```

mf2py currently replaces all backcompat classes with mf2 equivalent and adds a `data` element to parse the `rel-tag` and these replacements then show up in the parsed `content.html`
