### ISSUE TITLE
cut a release

### ISSUE THREAD

**Issue by snarfed** [microformats/mf2py#102]
@kartikprabhu has made some great improvements recently. i can't wait to see them released so i can use them!

i know you all are already working on this; just filing an issue in case it helps track. related to #93.

**Comment by snarfed** [comment]
friendly ping?

**Comment by kartikprabhu** [comment]
@snarfed sorry got busy with real work stuffs. Will review this weekend and plan for a release.

**Comment by snarfed** [comment]
no worries, thank you!

**Comment by snarfed** [comment]
woo! thank you!!!

**Comment by kartikprabhu** [comment]
@kevinmarks released new version out. Could you close this issue along with #103 #82 #80 #77 #75  #39 ?

**Comment by snarfed** [comment]
done! sorry for the delay. feel free to close issues yourself btw, no need to wait for me! :P
