### ISSUE TITLE
Bad implied p-name for implied h-feed

### ISSUE THREAD

**Issue by singpolyma** [microformats/mf2py#103]
https://python.microformats.io/?url=https%3A%2F%2Fsingpolyma.net%2Fcategory%2Ftech%2F&parser=html5lib

```
If no "h-feed" nor "hfeed" element is found, however multiple top-level h-entry elements (explicit or backcompat) are found, implementations may use:

top level h-entry elements as items in a synthetic h-feed.
<title> of the page or the URL of the page as p-name
```

http://microformats.org/wiki/h-feed#Parser_Compatibility

But instead the implied h-feed gets a p-name of all the text in the whole feed.

**Comment by kartikprabhu** [comment]
also you seem to have an explicit `hfeed` in your markup.

The implied properties parsing was recently changed to not parse for implied-name when parsing backcompat mf roots. This will be in a future release on mf2py.
