### ISSUE TITLE
deepcopy error on <use> inside <svg>

### ISSUE THREAD

**Issue by kartikprabhu** [microformats/mf2py#108]
mf2py v1.1.1 makes a copy of the given BS document to avoid making changes to the original one given by the user (see https://github.com/microformats/mf2py/blob/master/mf2py/parser.py#L111).

This fails if the markup contains a `<use>` tag, usually used inside a `<svg>` to create icon sprites. Following is a minimal example
```python
import copy
from bs4 import BeautifulSoup
from bs4.element import Tag

doc = '''<svg ><use xlink:href="some-svg-part"></use></svg>'''
soup = BeautifulSoup(doc, features='html5lib')
svg = soup.svg
use = soup.use

# check that <use> is a Tag
isinstance(use, Tag)
# returns: True

use['xlink:href']
# returns: 'some-svg-part'

copy.deepcopy(use)
# throws TypeError

copy.copy(use)
# works

copy.deepcopy(svg) 
# throws TypeError
```
Note, no error is thrown if the HTML is instead `<svg ><use xlink:href="some-svg-part"></use></svg>` i.e. using `href` instead of `xlink:href`. So this seems to be due to using `html5ib` to parse XML, but everything parses fine except we can't make a deepcopy!

 `href:xlink` is useful for maximum browser compatibility (see: https://kartikprabhu.com/articles/href-in-svg ).

cc: @kevinmarks @snarfed @sknebel 

PS: I noticed this because my Atom feed broke on switching to new mf2py. I generate Atom from `h-feed`.

**Comment by sknebel** [comment]
Appears BS4 only promises deep-copyability for trees based on HTMLParser. Good news: [copy.copy is overwritten in it to provide a deepcopy like function](https://bazaar.launchpad.net/~leonardr/beautifulsoup/bs4/view/head:/bs4/element.py#L868), so it seems like that's the function to use here.

**Comment by kartikprabhu** [comment]
attempted a fix here https://github.com/kartikprabhu/mf2py/commit/8a206624ba4471c1b7b0725a75261b697c0458f3

but this fails the crucial test https://github.com/kartikprabhu/mf2py/blob/experimental/test/test_parser.py#L592 and I have no idea why or how!

**Comment by sknebel** [comment]
sadly, the copy provided by bs4 is broken for Tags. I have thus replaced it with a custom one for now (and will be filing an upstream issue). To note is also that the cloning of Soup objects works by serializing and reparsing the entire tree, potentially expensive, but I did not feel comfortable to completely replace this now.

**Comment by kartikprabhu** [comment]
@sknebel I ma not sure that the `copy` function is actually broken on `Tag`. Here is an example that works outside mf2py

```python
import copy
from bs4 import BeautifulSoup

doc = '''<article class="hentry"></article>'''
soup = BeautifulSoup(doc)

art1 = copy.copy(soup.article)
art1['class'] = 'boo'
art1['href'] = 'example.com'

art1
# returns: <article class="boo" href="example.com"></article>

soup.article
# returns: <article class="hentry"></article>

soup
# returns: <html><head></head><body><article class="hentry"></article></body></html>
```

**Comment by kartikprabhu** [comment]
oh wow! Yeah, you are right. Cool will look at the PR

**Comment by sknebel** [comment]
@snarfed not directly, but same location clearly, so changes here will impact it too. Recursion depth exceeded... can you share the page causing the problem?

**Comment by snarfed** [comment]
i tried the fix in #114, and it looks good. no longer crashing on bridgy.

@sknebel i think the page that triggered it is somewhere on http://tilde.club/~schussat/ , or maybe on http://prettygoodhat.com/ . i haven't tracked down exactly where yet.

**Comment by snarfed** [comment]
bridgy log is https://brid.gy/log?start_time=1532442759&key=aglzfmJyaWQtZ3lyFgsSB1R3aXR0ZXIiCXNjaHVzc21hbgw

**Comment by sknebel** [comment]
With the revert of the deepcopy stuff and replacing it with the limited BS4 copy, this shouldn't be able to happen anymore.
