### ISSUE TITLE
Need to switch over to proper testing using existing test suites

### ISSUE THREAD

**Issue by tommorris** [microformats/mf2py#11]
---
- Bitbucket: https://bitbucket.org/tommorris/mf2py/issue/9
- Originally Reported By: [Tom Morris](http://bitbucket.org/tommorris)
- Originally Created At: 2013-11-07T00:40:45.364

**Comment by kevinmarks** [comment]
I have this mostly working in my fork, using a fork of the mf2 tests too. 
https://github.com/tommorris/mf2py/compare/master...kevinmarks:master
