### ISSUE TITLE
crashes with lxml, maybe other BeautifulSoup parsers

### ISSUE THREAD

**Issue by snarfed** [microformats/mf2py#110]
i get this crash when i pass mf2py a BeautifulSoup instance that uses the lxml parser (which BeautifulSoup claims is the fastest and best: http://www.crummy.com/software/BeautifulSoup/bs4/doc/#specifying-the-parser-to-use ):

```
Traceback (most recent call last):
...
  File "/Users/ryan/src/bridgy/original_post_discovery.py", line 416, in _find_feed_items
    parsed = util.mf2py_parse(feed_doc, feed_url)
  File "/Users/ryan/src/bridgy/util.py", line 693, in mf2py_parse
    return mf2py.parse(url=url, doc=input)
  File "/Users/ryan/src/mf2py/mf2py/parser.py", line 44, in parse
    return Parser(doc, url, html_parser, img_with_alt).to_dict()
  File "/Users/ryan/src/mf2py/mf2py/parser.py", line 125, in __init__
    self.__html_parser__ = self.__doc__.builder.NAME
AttributeError: 'LXMLTreeBuilder' object has no attribute 'NAME'
```

looks like that line was introduced in 1.1.1, in 83723fb2a00c6f19b8c22c64410c0b947652ae32:

https://github.com/microformats/mf2py/blob/fd4167df51ca6a7c20873647b4fff3193dbd4db3/mf2py/parser.py#L122-L127

cc @kartikprabhu

**Comment by sknebel** [comment]
This seems fairly straightforward to fix... but I can't reproduce it. Can you provide me a code snippet that breaks?

**Comment by sknebel** [comment]
... not for me, tested both on Py3(.6) and Py2(.7.9). LXMLTreeBuilder in BS4 also [clearly has that property](https://bazaar.launchpad.net/~leonardr/beautifulsoup/bs4/view/head:/bs4/builder/_lxml.py#L240), so I don't really understand what's going on, your BS4 would have to be seriously out of date to miss that.

**Comment by kartikprabhu** [comment]
@snarfed BeautifulSoup is on 4.6.0 now so it seems your BS is very outdated!

@sknebel Thanks for debugging this in detail!

**Comment by kartikprabhu** [comment]
that is even more weird. pip upgrades things for me fine with the current setup

**Comment by snarfed** [comment]
example:

```py
https://github.com/snarfed/granary/blob/1b4627e2dba932dfbec0b7d4ae1097b218060ef8/setup.py#L45-L58
```

moving to IRC...
