### ISSUE TITLE
Extracting all links

### ISSUE THREAD

**Issue by mardy** [microformats/mf2py#154]
Hi there!
  I'm working on a python module to implement [the webmention protocol](https://www.w3.org/TR/webmention/); one thing my module should do is to check that a certain remote webpage contains a given URL. If this condition is satisfied, then it should extract some additional data from the webpage (such as the author's name and e-mail). For this latter step I thought of using `mf2py`, but then I thought that I could optimize things a little if `mf2py` was able to perform both steps.

Unfortunately, while I see that `mf2py` extracts lots of links from the webpage, most URLs pointing to external resources are missing (I've been trying on [this blog post](http://phototeleport.com/2019/08/15/facebook-test/), for example, which contains the link `http://www.mardy.it/blog/2019/02/growing-up-or-leaving-facebook.html` which I'd like to get returned in the parsed list). I do understand that `mf2py` is acting correctly here, if the links are not properly marked according to the microformats specification, so this is not really a bug.

However, is there any way to optimize the way I can use `mf2py` for my use-case? I'm willing to contribute a patch, if you give me a hint on what would be an acceptable API. Maybe an additional named parameter to `parse()`, such as `extract_all_links=True` (set to `False` by default, of course) and that would create an additional field in the returned object, like the `other-urls` list below:
```
{
  'items': [],
  'debug': {
    'description': 'mf2py - microformats2 parser for python',
    'version': '1.1.2',
    'markup parser': 'html5lib',
    'source': 'https://github.com/microformats/mf2py'
  },
  'alternates': [
    {
      'type': 'application/atom+xml',
      'title': 'PhotoTeleport',
      'url': 'http://www.phototeleport.com/feed.xml',
      'text': ''
    }
  ],
  'rel-urls': { ... },
  'other-urls': [
    'http://www.mardy.it/blog/2019/02/growing-up-or-leaving-facebook.html',
    'https://gitlab.com/mardy/photokinesis/issues',
  ]
}
```

**Comment by mardy** [comment]
Only now I realize that the `parse()` method can also take a `BeautifulSoup` document. So one way to achive my goal is to retrieve and parse the webpage myself using `BeautifulSoup`, and pass the parsed document to `parse()`.

This is good enough for me, so I'm closing this :-)

**Comment by tommorris** [comment]
Hi @mardy, sorry I didn't get back to this earlier—the solution you've found is great, and I'm glad it works for you. Thanks.
