### ISSUE TITLE
Python: BeautifulSoup not extracting all rows in a Table

### ISSUE THREAD

**Issue by upchair** [microformats/mf2py#156]
Hello all,

Please I am trying to scrape all rows in a table via the link (https://en.wikipedia.org/wiki/List_of_state_and_union_territory_capitals_in_India). As you can see via the table there are 37 rows. However, my beautifulsoup method is only able to extract  rows 5 To 37.

It does not extract rows 1 To 4.

I would be grateful if anybody can tell me why this is happening and also give a solution to the problem.

Please see my code below. Thank You.

...............................................................................................................................................

import requests
import bs4
import pandas as pd

from bs4 import BeautifulSoup

page = requests.get('https://en.wikipedia.org/wiki/List_of_state_and_union_territory_capitals_in_India')
soup = bs4.BeautifulSoup(page.content, 'html.parser')
right_table=soup.find("table", class_="wikitable sortable plainrowheaders").text

print(right_table)

**Comment by tommorris** [comment]
Not relevant to mf2py.
