### ISSUE TITLE
Handle BeautifulSoup warning better

### ISSUE THREAD

**Issue by tommorris** [microformats/mf2py#158]
Currently, in CI, we get:

```
test/test_parser.py:48: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 48 of the file /home/travis/build/microformats/mf2py/test/test_parser.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.
```

Might be nice to fix this.

**Comment by capjamesg** [comment]
I believe this can be fixed by explicitly specifying a parser= parameter. In this case, parser=“lxml” seems prudent. I can make this change in a small PR if you would like :)

**Comment by tommorris** [comment]
@capjamesg Thanks for offering. I've sorted this out - it required fixing the CI setup. There's a few other minor irritations that need doing on this repo to bring it up-to-date.
