### ISSUE TITLE
Add hListing and backcompat support

### ISSUE THREAD

**Issue by tommorris** [microformats/mf2py#17]

**Comment by kartikprabhu** [comment]
There are no current rules for backcompat parsing of hListing http://microformats.org/wiki/hListing and h-listing http://microformats.org/wiki/h-listing does not seem to be used much.

**Comment by capjamesg** [comment]
I am going to close this issue since it has been inactive for a long period of time without discussion. If this issue is still relevant, feel free to re-open it and we can continue discussing it. Thanks!
