### ISSUE TITLE
Ignore Tailwind's h- prefix values

### ISSUE THREAD

**Issue by tommorris** [microformats/mf2py#170]
Tailwind is a CSS framework that uses h- prefixed values for styling, specifically [height](https://tailwindcss.com/docs/height).

Therefore, the following example won't parse well in any correct implementation of microformats2.

```html
<html class="h-full">
...
<span class="h-card p-name">Johnny Appleseed</div>
...
</html>
```

The options for dealing with this seem to be:

1. make Tailwind go away permanently (honestly, I'm not a fan, but each to their own)
2. tell HTML authors to not use Tailwind with height properties if they're also using microformats2
3. ignore Tailwind's height properties (by default, ideally there should always be a way to get strict parsing) - the parsing spec apparently already excludes `h-[0-9]*` but we could also the other `h-` properties used by Tailwind

Given Tailwind doesn't seem to be going away, and given [priority of constituencies](https://www.w3.org/TR/html-design-principles/#priority-of-constituencies) ("consider users over authors over implementors over specifiers over theoretical purity"), the third option may be the least bad, even if it does make parsing marginally more complicated.

**Comment by sknebel** [comment]
this should be an issue against the microformats spec, not mf2py

**Comment by snarfed** [comment]
specifically https://github.com/microformats/microformats2-parsing/issues ?

**Comment by gRegorLove** [comment]
Agreed, parsing specification issue. However the ability to parse prefixes without needing to know anything about a specific microformat is one of the key improvements in mf2 vs mf1, so I'm not sure there's an easy resolution.

**Comment by tommorris** [comment]
Okay, filed an issue there too.

**Comment by angelogladding** [comment]
If we're going to worry about preempting this conflict I believe we should do it via a block list and not an allow list.

If the fix is simple a block list can be easily adapted (as Tailwind evolves and other popular products clobber the class namespace). Incompleteness is acceptable.

An allow list on the other hand would require a gatekeeping of sorts and a known benefit of microformats is a convergent vocabulary. Incompleteness is unacceptable.
