### ISSUE TITLE
Should we drop trailing ? in rel-urls when there's no query string?

### ISSUE THREAD

**Issue by snarfed** [microformats/mf2py#177]
I'm seeing an odd bug. Looking at https://python.microformats.io/?url=https%3A%2F%2Ftantek.com%2F&parser=html5lib , the `rel-urls` item for `https://tantek.com/` has `text` `""`, but it should be the emoji :house:. Other emoji show up fine in `text` eg `https://tantek.com/?skin=vtx` correctly has :tv: :

```json
 "rel-urls": {
  "https://tantek.com/": {
   "text": "",
   "rels": [
    "author",
    "canonical",
    "nofollow",
    "openid.delegate",
    "self"
   ],
   "title": "Choose default theme"
  },
  "https://tantek.com/?skin=vtx": {
   "text": "\ud83d\udcfa",
   "rels": [
    "nofollow"
   ],
   "title": "Choose Terminal theme"
  },
  "..."
```

Fwiw the :house: comes through fine in php-mf2, https://pin13.net/mf2/?url=https://tantek.com/

**Comment by snarfed** [comment]
False alarm! Not an emoji parsing issue. 🏠 is coming through fine, it's just attached to `https://tantek.com?` with a trailing question mark. I was confused because php-mf2 evidently strips the empty `?` and merges it into the other `https://tantek.com` (without `?`) rel-url.

**Comment by snarfed** [comment]
Is that merging the correct behavior? Should mf2py do it? @tantek @kevinmarks 🤷🤷🤷

**Comment by angelogladding** [comment]
The following HTML:

```html
<a href=/? rel=foo>bar</a>
```

with URL: `https://example.com`

parses on php.microformats.io to:

```json
{
    "items": [],
    "rels": {
        "foo": [
            "https://example.com/"
        ]
    },
    "rel-urls": {
        "https://example.com/": {
            "text": "bar",
            "rels": [
                "foo"
            ]
        }
    },
    "debug": {...}
}
```

and on python.microformats.io to:

```json
{
 "items": [],
 "rels": {
  "foo": [
   "https://example.com/"
  ]
 },
 "rel-urls": {
  "https://example.com/": {
   "text": "bar",
   "rels": [
    "foo"
   ]
  }
 },
 "debug": {...}
}
```

Considering the original problem is no longer applicable I'm going to close this issue.
