### ISSUE TITLE
mf2py live tester on heroku 500 error

### ISSUE THREAD

**Issue by kartikprabhu** [microformats/mf2py#18]
mf2py live-tester gives an Internal Sever Error on (500) on:

https://mf2py.herokuapp.com/parse?url=https%3A%2F%2Fkartikprabhu.com

**Comment by capjamesg** [comment]
I am going to close this issue seeing as this has been open since 2014 without further discussion. You can use the official [microformats2 Python testing environment](https://python.microformats.io) for web testing.
