### ISSUE TITLE
Move to use pyproject.toml

### ISSUE THREAD

**Issue by angelogladding** [microformats/mf2py#180]
https://packaging.python.org/en/latest/tutorials/packaging-projects/ revolves around pyproject.toml and makes no mention of setup.py.

We should move to pyproject.toml.

@tommorris has moved in this direction with https://github.com/microformats/mf2py/pull/166 but I'd say there's a few more things to consider in the transition:

- setup.py currently imports the version number from `mf2py.version`
  - The **Note:** in the first technique listed at https://packaging.python.org/en/latest/guides/single-sourcing-package-version/ describes a variation of this for use in a pyproject.toml
- setup.py will no longer be necessary

## Should we use `poetry`?

I only have experience with poetry. The alternatives are pip-tools and pipenv, see https://packaging.python.org/en/latest/guides/tool-recommendations/

Of those only pipenv and poetry aid you throughout the entire lifecyle of the project. I believe poetry has the better developer experience.

*pipenv uses pipfile where poetry uses pyproject.toml*

- poetry.lock is not typically recommended for inclusion in VCS *for libraries*, see https://python-poetry.org/docs/basic-usage/#commit-your-poetrylock-file-to-version-control
- requirements.txt can be auto-generated if desired, see https://python-poetry.org/docs/cli#export

**Comment by capjamesg** [comment]
This has been completed and merged into `main`.
