### ISSUE TITLE
Resolve relative URLs in e-* HTML content

### ISSUE THREAD

**Issue by snarfed** [microformats/mf2py#181]
Inspired by https://github.com/snarfed/bridgy-fed/issues/390#issuecomment-1408879534, open parsing issue https://github.com/microformats/microformats2-parsing/issues/38, related implementation details in https://github.com/microformats/mf2py/issues/138.

**Comment by angelogladding** [comment]
From the [HTML attributes table][1] referenced in @Zegnat's proposal I see the following URL attributes:

- cite, data, href, src, poster
- ping
- action, formaction
- itemid, itemprop, itemtype

Do we need to support ping, forms or microdata?

[1]: https://html.spec.whatwg.org/multipage/indices.html#attributes-3

Can this wait until after the transition to py3?

**Comment by snarfed** [comment]
Thanks! I expect it's fine to ship an initial implementation of this with just the first line: href, src, cite, data, poster, probably in that priority order. The rest seem very low priority and/or unwanted entirely.

(Also mf2py migrated to python 3 ages ago, that's not a blocker here.)

**Comment by angelogladding** [comment]
Oops, I meant to say "transition *away* from py2" or "transition to py3 *only*".

With py3 wheels we can install lxml without having to compile and thus it's possible to add it as a core dependency.

If that were to be the case we could use their machinery: https://lxml.de/lxmlhtml.html#working-with-links

Here's their code: https://github.com/lxml/lxml/blob/11b33a83ad689bd16bd0a98c14cda51a90572b73/src/lxml/html/__init__.py#L435

It's a bit of a stretch but also a nod toward feature freeze in anticipation of deprecation of py2.

**Comment by angelogladding** [comment]
`lxml` does *not* make relative `srcset` items absolute and I see now that other properties are already being made absolute.

I'll work on support for `cite, data, href, src, poster`. I imagine `srcset` on an `img` found inside the `e-*` should be made absolute as well.

**Comment by JKingweb** [comment]
I went through this exercise a few weeks ago, and compiled a list of URL-holding attributes from the HTML, MathML 3, and SVG Tiny specifications:

- action on form
- altimg on math:math
- cdgroup on math:math
- cite on blockquote, del, ins, q
- data on object
- definitionURL on math:*
- formaction on button, input
- handler on svg:listener
- href on a, area, base, link, math:*
- itemid on html:*
- itemprop on html:*
- itemtype on html:*
- ping on a, area
- src on audio, embed, iframe, img, input, script, source, track, video, math:mglyph, math:share, math:annotation, math:annotation-xml
- xlink:href on svg:*, math:*
- xlink:role on svg:*, math:*
- xlink:arcrole on svg:*, math:*
- xml:base on svg:*, math:*

Then you also have image candidate strings (comma-separated):

- imagesrcset on link
- srcset on img, source

And finally, URL token-lists (whitespace-separated):
- macros on math:math
- requiredExtensions on svg:a, svg:animate, svg:animateColor, svg:animateMotion, svg:animateTransform, svg:animation, svg:audio, svg:circle, svg:desc, svg:discard, svg:ellipse, svg:foreignObject, svg:g, svg:image, svg:line, svg:metadata, svg:path, svg:polygon, svg:polyline, svg:rect, svg:set, svg:switch, svg:tbreak, svg:text, svg:textArea, svg:title, svg:tspan, svg:use, svg:video
- requiredFeatures on svg:a, svg:animate, svg:animateColor, svg:animateMotion, svg:animateTransform, svg:animation, svg:audio, svg:circle, svg:desc, svg:discard, svg:ellipse, svg:foreignObject, svg:g, svg:image, svg:line, svg:metadata, svg:path, svg:polygon, svg:polyline, svg:rect, svg:set, svg:switch, svg:tbreak, svg:text, svg:textArea, svg:title, svg:tspan, svg:use, svg:video

Of all these href on base is a special case (its own value is not considered for resolution), as is xml:base. Attributes on foreign elements should probably also perform xml:base resolution in addition to HTML base resolution.

**Comment by angelogladding** [comment]
@JKingweb what do you think about supporting the minimal case for now? https://github.com/microformats/mf2py/pull/201/files#diff-746fcc4c80a0a67fedb71d5bed24ae4a0e4925083edd63a8cef66eadc69a4cb3R100
