### ISSUE TITLE
Switch img alt parsing to on by default

### ISSUE THREAD

**Issue by snarfed** [microformats/mf2py#182]
It's been over 3 yrs [since this was officially incorporated into the spec](https://github.com/microformats/microformats2-parsing/issues/2#issuecomment-450712178), 4-5 yrs since #83 and https://github.com/kartikprabhu/mf2py/issues/56. img alt parsing is pretty standard and expected now, and it trips people up when they don't know they need to turn it on with `img_with_alt=True`. It's probably time to drop the feature flag, or at least switch it to on by default!

cc @ludovicchabant

**Comment by gRegorLove** [comment]
Agreed. img-alt parsing has been live in php-mf2 [since 2022-02-09](https://github.com/microformats/php-mf2/releases/tag/v0.5.0).

**Comment by capjamesg** [comment]
I have filed a PR to implement this (PR #184). @snarfed I have tagged you as a reviewer.

**Comment by sknebel** [comment]
For context, this has gotten "stuck" because it's a breaking change and there were more things on the list before doing a major version change before this all fell asleep. I'd propose to do the change Python3 only and then make a major version jump.

**Comment by capjamesg** [comment]
I agree. Python 2.7 and 3.6 deprecation, and the corresponding test suite environment fixes, is at the top of the TODO list.

**Comment by capjamesg** [comment]
The PR implementing this (#184) has been merged and will be included in the next release.
