### ISSUE TITLE
Need documentation for PyPI package

### ISSUE THREAD

**Issue by tommorris** [microformats/mf2py#2]
We need some basic usage instructions for the PyPI package page, written in ReStructuredText with code samples.

**Comment by capjamesg** [comment]
@tommorris Is this still a need? I’d be really happy to give this a crack in a PR.

**Comment by snarfed** [comment]
@capjamesg thanks! We actually did this a while ago, https://pypi.org/project/mf2py/ now uses README.md as the package description. Thanks for the nudge. There's still plenty to help with in #164 if you're interested though!
