### ISSUE TITLE
Missing whitespace before img alt/src in text content

### ISSUE THREAD

**Issue by snarfed** [microformats/mf2py#202]
@JoelOtter discovered an odd little possible mf2py bug in https://github.com/snarfed/bridgy/issues/1527 : when `e-content`/`p-content` contains a a `p` followed immediately by an `img`, without whitespace separating them, mf2py adds the `img`'s `alt` or `src`, as expected, but doesn't include a leading space. [Lots more discussion in #dev a couple days ago.](https://chat.indieweb.org/microformats/2023-07-27#t1690476868138000)

Example:

```html
<div class="h-entry">
<div class="e-content">
<p>foo</p><img src="pic.png" alt="bar">baz
</div>
</div>
```

parses to:

```json
{
  "items": [{
      "type": ["h-entry"],
      "properties": {
        "content": [{
            "html": "<p>foo</p><img alt=\"bar\" src=\"pic.png\"/>baz",
            "value": "foobar baz"
        }],
        "photo": ["pic.png"]
      }
  }],
}
```

Note that there's no space between `foo` and `bar` in `content.value`. Same thing happens with `p-content`. Interestingly it _doesn't_ happen if I remove the `p` around `foo`, mf2py then correctly adds a space.

From https://microformats.org/wiki/microformats2-parsing#parsing_an_e-_property :
> replacing any nested <img> elements with their alt attribute, if present; otherwise their src attribute, if present, adding a space at the beginning and end, resolving the URL if it’s relative;

cc @capjamesg

**Comment by angelogladding** [comment]
Images are already being wrapped with spaces https://github.com/microformats/mf2py/blob/main/mf2py/dom_helpers.py#L111.

The problem here is that whitespace around paragraphs is being stripped. See PR #207.
