### ISSUE TITLE
using html.parser can give erroneous results

### ISSUE THREAD

**Issue by kevinmarks** [microformats/mf2py#36]
For example, parsing http://kevinmarks.tumblr.com/ will give the whole body text in the text of rel-urls, because of how html.parser munges a &lt;link&gt; that isn't closed.
html5lib and lxlml don't seem to have this problem.

**Comment by kylewm** [comment]
I think we can exclude html.parser by specifying features='permissive' to the BeautifulSoup constructor. lxml and html5lib are both categorized as 'permissive', which html.parser is 'strict'

**Comment by sknebel** [comment]
we attempt to select a better parser by default. closing this, since it doesn't seem to have an actionable request.
