### ISSUE TITLE
<br> tags are not interpreted as whitespace when converting HTML to plaintext

### ISSUE THREAD

**Issue by kylewm** [microformats/mf2py#51]
original: https://github.com/indieweb/php-mf2/issues/69

**Comment by kylewm** [comment]
we've got a PR to refer to now too, thanks @gRegorLove https://github.com/indieweb/php-mf2/pull/82

**Comment by kartikprabhu** [comment]
also https://pin13.net/mf2/whitespace.html which is for v1.0.5 at the moment

**Comment by kartikprabhu** [comment]
fixed in v1.1.1
