### ISSUE TITLE
add shortlink to backcompat classes

### ISSUE THREAD

**Issue by kylewm** [microformats/mf2py#52]
Discussed in snarfed/bridgy#173
And based on http://microformats.org/wiki/rel-shortlink#Abstract

we should add rel=shortlink like rel=bookmark to the hentry-scoped rel-properties, and also backcompat support for interpreting class=shortlink as class=u-shortlink.

**Comment by snarfed** [comment]
snarfed/bridgy#173

**Comment by kylewm** [comment]
oops, sorry, thank you for catching

**Comment by kartikprabhu** [comment]
Neither http://microformats.org/wiki/h-entry#Backward_Compatibility nor http://microformats.org/wiki/rel-shortlink defines any backcompat parsing for rel-shortlink

**Comment by capjamesg** [comment]
I am going to close this issue since it has been inactive for a long period of time without discussion. If this issue is still relevant, feel free to re-open it and we can continue discussing it. Thanks!
