### ISSUE TITLE
mf2py should use py.test

### ISSUE THREAD

**Issue by tommorris** [microformats/mf2py#66]
py.test looks like it is the future of testing in Python and nose is falling into obscurity. Lots of libraries have switched over already. Anyone got any good reason mf2py shouldn't?

**Comment by kylewm** [comment]
I've used and liked py.test on other projects; porting over should be pretty trivial. Bridgy and friends just use unittest, and that's also fine (but would require a little more work to port the existing tests)

**Comment by snarfed** [comment]
Merging into #175.
