### ISSUE TITLE
Separate out the backcompat rules into JSON

### ISSUE THREAD

**Issue by tommorris** [microformats/mf2py#70]
See http://indiewebcamp.com/irc/2016-05-17/line/1463494157321 for more details

**Comment by kylewm** [comment]
I think making the backcompat rules extensible is a great idea -- but I'd favor exposing/documenting the extension points in Python rather than adding a config file format (that I fear will grow into a DSL for describing XML transformations)

**Comment by tommorris** [comment]
@kylwm: I can see why that's a bad idea, but there's some upside too.

Given the existing alternative is something nasty like XSLT, a constrained DSL for describing these transformations in JSON means we can share the backcompat transformations between mf2py and other mf2 implementations. We share test suites with the other implementations. It'd be nice if we could move more of the microformats-specific logic into a language-neutral form.

**Comment by kartikprabhu** [comment]
I like the idea of moving backcompat rules into JSON to be shared among parsers. I propose the following format for the files for each mf1root containing a JSON object e.g. `hentry.json`
```json
{
    "type": ["h-entry"],
    "properties": {
        "entry-title": ["p-name"],
        "entry-summary": ["p-summary"],
        "entry-content": ["e-content"],
        "published": ["dt-published"],
        "updated": ["dt-updated"],
        "author": ["p-author", "h-card"],
        "category": ["p-category"],
        "geo": ["p-geo", "h-geo"],
        "latitude": ["p-latitude"],
        "longitude": ["p-longitude"]
    }
}
```
Here `type` gives the mf2 equivalent roots, while each item in the `properties` object gives the mf2 equivalent properties.

Possibly can be done in a new repo backcompat-rules?

cc: @gregorLove @tantek @kevinmarks @aaronpk

**Comment by Zegnat** [comment]
> Possibly can be done in a new repo backcompat-rules?

As I have argued for an authorative list of backcompat classes (see https://github.com/microformats/microformats2-parsing/issues/13) having a project that formally defines all of it in a centralised place sounds good to me. Even if parser implementers choose to not rely on the specific JSON files it will provide them with an easily accessible mapping.

**Comment by kartikprabhu** [comment]
Here is a sample of the current rules in mf2py dumped in the above format

https://github.com/kartikprabhu/backcompat-rules

**Comment by kartikprabhu** [comment]
Updated https://github.com/kartikprabhu/backcompat-rules with rules for `rels` so now `hentry.json` looks like
```json
{
    "type": [
        "h-entry"
    ], 
    "properties": {
        "category": [
            "p-category"
        ], 
        "entry-title": [
            "p-name"
        ], 
        "published": [
            "dt-published"
        ], 
        "latitude": [
            "p-latitude"
        ], 
        "entry-content": [
            "e-content"
        ], 
        "entry-summary": [
            "p-summary"
        ], 
        "author": [
            "p-author", 
            "h-card"
        ], 
        "geo": [
            "p-geo", 
            "h-geo"
        ], 
        "updated": [
            "dt-updated"
        ], 
        "longitude": [
            "p-longitude"
        ]
    },
    "rels": {
        "bookmark": [
            "u-url"
        ],
        "tag": [
            "p-category"
        ]
    }
}
```
This new set is now under use in mf2py experimental to do all backcompat parsing https://github.com/kartikprabhu/mf2py/tree/experimental
