### ISSUE TITLE
Add ability to export iCalendar

### ISSUE THREAD

**Issue by tommorris** [microformats/mf2py#71]
One of the benefits of the old microformats parsers was the ability to export the data out in a variety of useful formats beyond JSON: iCalendar, vCard, and Atom.

It'd be useful to have an iCalendar output.

**Comment by capjamesg** [comment]
@snarfed Is this still relevant? The broader question, too, is whether munging between formats is in scope for a parsing library.

**Comment by snarfed** [comment]
Agreed on the broader question! It's a nice idea, but I vote it's now out of scope, let's leave conversion to downstream tools like https://h2vx.com/ics/ , granary, etc.

**Comment by capjamesg** [comment]
Thank you! In that case, I will close this conversation.
