### ISSUE TITLE
Backcompat conflict

### ISSUE THREAD

**Issue by aaronpk** [microformats/mf2py#75]
I am not 100% sure this is a bug in the implementation or a bug in the spec, so let me know if you can tell. My new h-review posts also have backcompat hReview classes. So far, the Python parser is the only one that gets them even remotely correct. ([Node parser issue](https://github.com/glennjones/microformat-node/issues/40), [PHP parser issue](https://github.com/indieweb/php-mf2/issues/45))

The only thing that I didn't expect to see in the Python-parsed version was this extra `h-card` as a child element. It's coming from the `vcard` inside the `h-entry`, which I added there to indicate the reviewer for `hReview`. 

* Original post: https://aaronparecki.com/2016/12/15/16/dropvox
*  [python parsed](http://www.unmung.com/mf2?url=https%3A%2F%2Faaronparecki.com%2F2016%2F12%2F15%2F16%2Fdropvox&html=&pretty=on)

Based on the mf2 wiki, I'm not totally clear whether this should be ignored or not: http://microformats.org/wiki/microformats2-parsing#note_backward_compatibility_details However, it was surprising to me that it's there, and I don't want it to show up in the mf2 parsed version.

**Comment by gRegorLove** [comment]
An mf2 parser should ignore the `reviewer vcard` because it's an mf1 inside an mf2 root. To make that reviewer information appear in an mf2 parser, a publisher should add `p-author h-card` to that same element. 

This is an issue in php-mf2 as well, which I'm working on currently.

**Comment by kartikprabhu** [comment]
fixed in #94
