### ISSUE TITLE
an mf2 class should override any mf1 (back-compat) class on the same element

### ISSUE THREAD

**Issue by snarfed** [microformats/mf2py#82]
discovered at IWS 2017 just now: if a tag has both mf2 and mf1 top-level classes, e.g. `<body class="post hentry h-event" ...>` on http://tantek.com/2017/179/e1/homebrew-website-club, right now mf2py says it's `type: ['h-event', 'h-entry']`...but @tantek says the mf2 class `h-event` should override the mf1 `hentry`, so the type should just be `['h-event']`.

(whee backcompat! :P)

**Comment by kartikprabhu** [comment]
fixed in #94
