### ISSUE TITLE
include img alt text in photo property

### ISSUE THREAD

**Issue by snarfed** [microformats/mf2py#83]
one drawback of the current mf2 spec is that img alt text is lost when a higher priority name property is provided, e.g. `p-name`. microformats/microformats2-parsing#2 proposes preserving alt text in e.g. the photo property by making it a composite object with a new `alt` field when alt text is available.

this is currently blocking a bridgy feature request, snarfed/bridgy#756, so i'd love to see it added to mf2py!

example: this HTML:

```html
<article class="h-entry">
  <span class="p-name">name</span>
  <img class="u-photo" src="/photo.jpg" alt="alt" />
</article>
```

would parse to this mf2:

```json
{
  "type": ["h-entry"],
  "properties": {
    "name": ["name"],
    "photo": [{
        "value": "/photo.jpg",
        "alt": "alt"
    }]
}
```

**Comment by snarfed** [comment]
friendly ping! cc @kylewm since he's worked on mf2py before too.

**Comment by snarfed** [comment]
now tracked (also? instead?) in https://github.com/kartikprabhu/mf2py/issues/56.

**Comment by snarfed** [comment]
hey @kartikprabhu any chance of getting this into the upcoming release?

**Comment by kartikprabhu** [comment]
unlikely. Haven't even started to code this up yet; also hugely breaking change and not in spec yet.

**Comment by snarfed** [comment]
as @tantek @aaronpk et al would say, specs are best when they describe and formalize already existing behavior, not prescribe new behavior before it's been implemented anywhere. :P

no worries though, happy to wait!

**Comment by sknebel** [comment]
Would it make sense to have feature flags for things like this, so consumers could opt-in to them at first, and them being switched on by default later?

**Comment by aaronpk** [comment]
We've done some feature flag stuff in the PHP parser to selectively enable new/experimental features.

**Comment by kartikprabhu** [comment]
Should implied photo also have the `alt` value?

Example:
```html
<article class="h-entry">
  <span class="p-name">name</span>
  <img src="/photo.jpg" alt="alt" />
</article>
```
