### ISSUE TITLE
Deprecate Python 2 support?

### ISSUE THREAD

**Issue by tommorris** [microformats/mf2py#87]
Are we ready to go Python 3 only? In 2020, Python 2.7 is going end-of-life. A bunch of popular Python projects including Django and Twisted have already announced Python 3 exclusivity. If we went to Python 3 support, we could add type annotations and so on.

Just as a quick survey: is there anyone using `mf2py` on Python 2? Do you have a plan to move to Python 3 soon?

**Comment by kevinmarks** [comment]
Yes, appengine classic is still 2.7 only, so both unmung and @snarfed's
appengine projects use it

**Comment by snarfed** [comment]
quite true. apologies!

I've made a lot of progress porting granary (and oauth-dropins) to at least python 3 compatible, using http://python-future.org , but i can't go python 3 only until app engine standard ships their support.

**Comment by tommorris** [comment]
That's a shame, but a pretty clear blocker. Apparently AppEngine is tied to Java 7 too. Google, always on the cutting edge, I guess. ;-)

**Comment by tommorris** [comment]
Can I nudge this again nearly four years later? Python 2.x is EOL, as is Python 3 before 3.6. [Google App Engine supports Python 3](https://cloud.google.com/appengine/docs/python/) and they no longer recommend 2.7 at all. It'd be really nice to finally end 2.x support.

The other way we can support 2.x is basically to say "all future builds will be 3-only, if you're running 2.x, you need to pin to 1.1.2 and we won't fix anything for 2.x anymore".

**Comment by snarfed** [comment]
Yes! Sounds great. My stuff all migrated to Python 3 a few years ago, so I'm ready. And yes, following semver and cutting a new major version is the right way to drop Python 2 support. Anyone who still needs it would pin to `<2.0`.

**Comment by sknebel** [comment]
Bridgy was pretty much the reason we wanted to keep Python 2 support for as long as we did, if it doesn't need it anymore I'd agree -> Python2 support can be deprecated.

**Comment by kevinmarks** [comment]
Pin to 1.1.2 sounds good to me, as GAE Python3 deprecates a huge pile of
useful tooling, so unmung will be running 2.x until I replace it entirely.

**Comment by angelogladding** [comment]
Should we press a 1.1.3 or 1.2 release before moving to 2.0?

https://packaging.python.org/en/latest/guides/dropping-older-python-versions/ describes using `python_requires` in setup.py to properly signal the deprecation -- eg. add python_requires='>=2.7' to a final 1.x release and then change to python_requires='>=3.7' in the following 2.x release.

**Comment by angelogladding** [comment]
https://github.com/microformats/mf2py/compare/main...angelogladding:mf2py:final-py2 is a start

**Comment by tommorris** [comment]
Thanks for looking into this, @angelogladding.

**Comment by angelogladding** [comment]
https://stackoverflow.com/a/56135899/6841359 describes bumping semver minor for a mark of deprecation--so jump to v1.2? Also, do we need to add a deprecation message to the README? 2.7 has been EOL since 2020-01-01 https://devguide.python.org/versions/

**Comment by capjamesg** [comment]
I have been pairing with @angelogladding on this. The test suite is no longer running properly because the `ubuntu-latest` environment to which the test suite is pinned no longer supports the Python versions stipulated in our Actions manifest. For us to get the test suite back up and running, we will need to deprecate support for v2.7 and v3.6, for which there is no supported environment in GitHub Actions. See https://github.com/actions/setup-python/issues/544 for more information on this point.

I propose that we make a final release with the repository in its current state and tag it as the final version for publication on v2.7 and v3.6, both versions of Python that have reached their End of Life.

**Comment by capjamesg** [comment]
cc'ing @kevinmarks @tantek @snarfed

**Comment by angelogladding** [comment]
Yes the deprecation of EOL python versions should come first. Modern systems won't support <3.7. I believe this is the correct path forward:

1) push a *minor* release with the `python_requires>=2.7` metadata added: https://github.com/microformats/mf2py/compare/main...angelogladding:mf2py:final-py2
2) remove python2 support: [`78c8f7f` (#179)](https://github.com/microformats/mf2py/pull/179/commits/78c8f7ff87225df764ff6c16addf2a65d41a982a)
3) keep working (pytest, poetry, linting, docs, img alt parsing, etc.)
4) add `python_requires>=3.7` and push a *minor* release
