### ISSUE TITLE
separate out the front end from parser code

### ISSUE THREAD

**Issue by kartikprabhu** [microformats/mf2py#91]
Currently the Heroku front end is in the same code base as the parser.

Might be better to separate out the frontend. I am not sure the Heroku instance is used anywhere

cc: @kevinmarks @snarfed

**Comment by snarfed** [comment]
oh wow, i didn't even know there was a heroku frontend. nice! consider adding it to the readme?

i don't have an opinion on where its code lives, but moving it sounds low priority, unless it's actively causing harm here somehow, which I'm guessing it's not...

**Comment by kartikprabhu** [comment]
well it isn't actively causing harm, but I suspect the Flask requirement is for the front_end.

For a parser that is simply a pretty heavy requirement to install.

**Comment by sknebel** [comment]
I assume it powers https://python.microformats.io/, which I guess @veganstraightedge set up, so moving it out should be coordinated there.

**Comment by tommorris** [comment]
Yeah, feel free to get rid of that. It is up at https://mf2py.herokuapp.com/ but python.microformats.io looks better.

**Comment by kartikprabhu** [comment]
@veganstraightedge would love your input on this issue. Do you use the in-built Heroku front end for mf2py on https://python.microformats.io/

**Comment by veganstraightedge** [comment]
Y’all do whatever you think is best and then tell me what if anything I need to do differently to update the deployed site. Don’t optimize for me. 👍🏻

**Comment by kartikprabhu** [comment]
@veganstraightedge I am assuming you are using https://github.com/veganstraightedge/mf2py-web instead on https://python.microformats.io/? I think that does not use the built-in Heroku app.

**Comment by veganstraightedge** [comment]
The website has a link to its source code in the footer.

It uses @kylewm's https://github.com/kylewm/mf2py-web

The repo on my user that you linked to was my fork to submit a pull request.

**Comment by tommorris** [comment]
Okay, it might be worth updating `README.md` to point to @veganstraightedge/mf2py-web and to https://python.microformats.io

Otherwise, happy to remove it, and I'll replace `mf2py.herokuapp.com` with a redirect to `python.microformats.io` - see issue #96.

**Comment by kartikprabhu** [comment]
@tommorris I want to go over kylewm's code to make sure this is not a problem. I can let you know or feel free to do make this change.
