### ISSUE TITLE
delete "icalendar" branch

### ISSUE THREAD

**Issue by kartikprabhu** [microformats/mf2py#92]
Not sure what the intent was with [branch:icalendar](https://github.com/microformats/mf2py/tree/icalendar) but it could be deleted.

**Comment by tommorris** [comment]
The idea with the icalendar branch was to try and build in the ability to convert to iCalendar format.

The idea would be to be able to call something like:

```
p = Parser(...)
p.to_ical()
```

And you'd get back text of all the v-event objects turned into iCalendar text, so you could spit that out for people to subscribe to in their calendar apps.

I never really finished it, but wouldn't mind keeping it around to work on at some point. 😔

**Comment by kartikprabhu** [comment]
@tommorris I was thinking it might be better to have enhanced uses of that sort as a separate library and keeping this code base purely for the parser. What do you think?

**Comment by snarfed** [comment]
iCalendar output support is tracked in #71. tentatively closing this issue.
